export const ROOMS_MOCKS = [
  {
    roomId: 'RgDxmhrka',
    name: 'belka',
    clients: 1,
    maxClients: 4,
    password: '123',
    bet: 100,
    eggsX4: true,
    dropAce: true,
    spas30: true,
    chat: true,
    fin120: true,
  },
  {
    roomId: 'RgDxmhrbk',
    name: 'belka',
    clients: 1,
    maxClients: 4,
    bet: 1000,
    eggsX4: false,
    dropAce: false,
    spas30: false,
    chat: false,
    fin120: false,
  },
  {
    roomId: 'RgDxmhrb',
    name: 'belka',
    clients: 3,
    maxClients: 4,
    bet: 1000,
    eggsX4: false,
    dropAce: false,
    spas30: false,
    chat: false,
    fin120: false,
  },
]
