export const mockState = {
  objects: {
    vjviuu0j: {
      id: 'vjviuu0j',
      type: 'Cards',
      ownerId: 'eyuuz61j',
      items: [],
      cardsSide: 'back',
    },
    dpkkznzk: {
      id: 'dpkkznzk',
      type: 'BelkaTeam',
      ownerId: 'eyuuz61j',
      index: 0,
      gameScore: 0,
      roundScore: 0,
      color: 'black',
    },
    n95uto39: {
      id: 'n95uto39',
      type: 'BelkaTeam',
      ownerId: 'eyuuz61j',
      index: 0,
      gameScore: 0,
      roundScore: 0,
      color: 'red',
    },
    j11wmo40: {
      id: 'j11wmo40',
      type: 'BelkaEggs',
      ownerId: 'eyuuz61j',
      active: false,
    },
    m27e6npe: {
      id: 'm27e6npe',
      type: 'Timer',
      ownerId: 'eyuuz61j',
      value: -1,
    },
    sqzfxns4: {
      id: 'sqzfxns4',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    h5qrte5e: {
      id: 'h5qrte5e',
      type: 'Card',
      ownerId: '2pkegt32',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    mhreowf3: {
      id: 'mhreowf3',
      type: 'Card',
      ownerId: 'xzkhax5l',
      side: 'face',
      data: {
        value: '7',
        suit: 2,
      },
    },
    '5f098n8v': {
      id: '5f098n8v',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '100gsr1u': {
      id: '100gsr1u',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '6hqqxl2b': {
      id: '6hqqxl2b',
      type: 'Card',
      ownerId: '2pkegt32',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    i17tkvec: {
      id: 'i17tkvec',
      type: 'Card',
      ownerId: 'knuzidc0',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    bzs1fft9: {
      id: 'bzs1fft9',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    rr3cayrg: {
      id: 'rr3cayrg',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    qd7vzrah: {
      id: 'qd7vzrah',
      type: 'Card',
      ownerId: '2pkegt32',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    e5yfcc3r: {
      id: 'e5yfcc3r',
      type: 'Card',
      ownerId: 'knuzidc0',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '4jkso3i4': {
      id: '4jkso3i4',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ysvxh1gs: {
      id: 'ysvxh1gs',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    slsml765: {
      id: 'slsml765',
      type: 'Card',
      ownerId: '2pkegt32',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    mxebh4oc: {
      id: 'mxebh4oc',
      type: 'Card',
      ownerId: 'knuzidc0',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '11u3i5h6': {
      id: '11u3i5h6',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ph3ns1re: {
      id: 'ph3ns1re',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '50jiyxba': {
      id: '50jiyxba',
      type: 'Card',
      ownerId: 'auldvbzh',
      side: 'face',
      data: {
        value: '10',
        suit: 2,
      },
    },
    p3717orr: {
      id: 'p3717orr',
      type: 'Card',
      ownerId: 'knuzidc0',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    wykc85oe: {
      id: 'wykc85oe',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    l0p6d69e: {
      id: 'l0p6d69e',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    saie1xy4: {
      id: 'saie1xy4',
      type: 'Card',
      ownerId: '2pkegt32',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    w4fsmein: {
      id: 'w4fsmein',
      type: 'Card',
      ownerId: 'knuzidc0',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '5759i721': {
      id: '5759i721',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    adagc3mq: {
      id: 'adagc3mq',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    q9qjaqqn: {
      id: 'q9qjaqqn',
      type: 'Card',
      ownerId: '2pkegt32',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    x4aqz3cg: {
      id: 'x4aqz3cg',
      type: 'Card',
      ownerId: 'knuzidc0',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    fyu85cpl: {
      id: 'fyu85cpl',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    y33st9qb: {
      id: 'y33st9qb',
      type: 'Card',
      ownerId: '1yhf19c9',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    w2uo3eqi: {
      id: 'w2uo3eqi',
      type: 'Card',
      ownerId: '2pkegt32',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    popaworc: {
      id: 'popaworc',
      type: 'Card',
      ownerId: 'knuzidc0',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '70qurbif': {
      id: '70qurbif',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    eyuuz61j: {
      id: 'eyuuz61j',
      type: 'BelkaBoard',
      ownerId: '',
      deckId: 'vjviuu0j',
      team1Id: 'dpkkznzk',
      team2Id: 'n95uto39',
      eggsId: 'j11wmo40',
      scene: 'gameRounds',
      timerId: 'm27e6npe',
    },
    pbe3rupk: {
      id: 'pbe3rupk',
      type: 'Timer',
      ownerId: 'j2gx87tw',
      value: 23,
    },
    f678cebv: {
      id: 'f678cebv',
      type: 'Cards',
      ownerId: 'j2gx87tw',
      items: ['mhreowf3'],
      cardsSide: 'face',
    },
    '1yhf19c9': {
      id: '1yhf19c9',
      type: 'Cards',
      ownerId: 'j2gx87tw',
      items: [
        'y33st9qb',
        'adagc3mq',
        'l0p6d69e',
        'ph3ns1re',
        'ysvxh1gs',
        'rr3cayrg',
        '100gsr1u',
        'sqzfxns4',
      ],
      cardsSide: 'back',
    },
    fqrlayly: {
      id: 'fqrlayly',
      type: 'Cards',
      ownerId: 'j2gx87tw',
      items: [],
      cardsSide: 'back',
    },
    j2gx87tw: {
      id: 'j2gx87tw',
      type: 'BelkaPlayer',
      ownerId: '',
      timerId: 'pbe3rupk',
      cardSlotId: 'f678cebv',
      handId: '1yhf19c9',
      suit: 1,
      score: 0,
      teamId: 'dpkkznzk',
      trashId: 'fqrlayly',
    },
    aqc2jf5o: {
      id: 'aqc2jf5o',
      type: 'Timer',
      ownerId: 'nrpd8cuu',
    },
    jrb0tkqj: {
      id: 'jrb0tkqj',
      type: 'Cards',
      ownerId: 'nrpd8cuu',
      items: ['mhreowf3'],
      cardsSide: 'face',
    },
    '8gzor99s': {
      id: '8gzor99s',
      type: 'Cards',
      ownerId: 'nrpd8cuu',
      items: [
        '70qurbif',
        'fyu85cpl',
        '5759i721',
        'wykc85oe',
        '11u3i5h6',
        '4jkso3i4',
        'bzs1fft9',
        '5f098n8v',
      ],
      cardsSide: 'back',
    },
    dbwkdsmb: {
      id: 'dbwkdsmb',
      type: 'Cards',
      ownerId: 'nrpd8cuu',
      items: [],
      cardsSide: 'back',
    },
    nrpd8cuu: {
      id: 'nrpd8cuu',
      type: 'BelkaPlayer',
      ownerId: '',
      timerId: 'aqc2jf5o',
      cardSlotId: 'jrb0tkqj',
      handId: '8gzor99s',
      suit: -1,
      score: 0,
      teamId: 'n95uto39',
      trashId: 'dbwkdsmb',
    },
    nxd9fbtu: {
      id: 'nxd9fbtu',
      type: 'Timer',
      ownerId: '2mzlnkdj',
      value: -1,
    },
    xzkhax5l: {
      id: 'xzkhax5l',
      type: 'Cards',
      ownerId: '2mzlnkdj',
      items: ['mhreowf3'],
      cardsSide: 'face',
    },
    knuzidc0: {
      id: 'knuzidc0',
      type: 'Cards',
      ownerId: '2mzlnkdj',
      items: ['popaworc', 'x4aqz3cg', 'w4fsmein', 'p3717orr', 'mxebh4oc', 'e5yfcc3r', 'i17tkvec'],
      cardsSide: 'back',
    },
    '2f45yb42': {
      id: '2f45yb42',
      type: 'Cards',
      ownerId: '2mzlnkdj',
      items: [],
      cardsSide: 'back',
    },
    '2mzlnkdj': {
      id: '2mzlnkdj',
      type: 'BelkaPlayer',
      ownerId: '',
      timerId: 'nxd9fbtu',
      cardSlotId: 'xzkhax5l',
      handId: 'knuzidc0',
      suit: -1,
      score: 0,
      teamId: 'dpkkznzk',
      trashId: '2f45yb42',
    },
    '4vpznqej': {
      id: '4vpznqej',
      type: 'Timer',
      ownerId: 'jb7uz57t',
      value: -1,
    },
    auldvbzh: {
      id: 'auldvbzh',
      type: 'Cards',
      ownerId: 'jb7uz57t',
      items: ['50jiyxba'],
      cardsSide: 'face',
    },
    '2pkegt32': {
      id: '2pkegt32',
      type: 'Cards',
      ownerId: 'jb7uz57t',
      items: ['w2uo3eqi', 'q9qjaqqn', 'saie1xy4', 'slsml765', 'qd7vzrah', '6hqqxl2b', 'h5qrte5e'],
      cardsSide: 'back',
    },
    '09xrblip': {
      id: '09xrblip',
      type: 'Cards',
      ownerId: 'jb7uz57t',
      items: [],
      cardsSide: 'back',
    },
    jb7uz57t: {
      id: 'jb7uz57t',
      type: 'BelkaPlayer',
      ownerId: '',
      timerId: '4vpznqej',
      cardSlotId: 'auldvbzh',
      handId: '2pkegt32',
      suit: -1,
      score: 0,
      teamId: 'n95uto39',
      trashId: '09xrblip',
    },
  },
  clients: {
    tNuvcWl40: {
      objectId: 'j2gx87tw',
      name: 'tim',
      rank: 1,
      score: 0,
      connected: true,
    },
    v1S3ZSH9I: {
      objectId: 'nrpd8cuu',
      name: 'tim3',
      rank: 1,
      score: 0,
      connected: true,
    },
    x7dges268: {
      objectId: '2mzlnkdj',
      name: 'Bot 0',
      rank: 1,
      score: 0,
      connected: true,
    },
    mf8puo4zli: {
      objectId: 'jb7uz57t',
      name: 'Bot 1',
      rank: 1,
      score: 0,
      connected: true,
    },
  },
  players: ['j2gx87tw', 'nrpd8cuu', '2mzlnkdj', 'jb7uz57t'],
  hand: {
    '70qurbif': {
      id: '70qurbif',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: '9',
        suit: 2,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
    fyu85cpl: {
      id: 'fyu85cpl',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: 'J',
        suit: 2,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
    '5759i721': {
      id: '5759i721',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: '10',
        suit: 0,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
    wykc85oe: {
      id: 'wykc85oe',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: 'K',
        suit: 3,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
    '11u3i5h6': {
      id: '11u3i5h6',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: '8',
        suit: 2,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
    '4jkso3i4': {
      id: '4jkso3i4',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: 'K',
        suit: 1,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
    bzs1fft9: {
      id: 'bzs1fft9',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: 'A',
        suit: 1,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
    '5f098n8v': {
      id: '5f098n8v',
      type: 'Card',
      ownerId: '8gzor99s',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
      face: {
        value: 'A',
        suit: 3,
      },
      back: {
        value: '',
        suit: 0,
      },
    },
  },
  actions: [],
  room: {
    hasJoined: true,
    id: 'y4SlB-TSE',
    serializer: {
      state: {
        clients: {
          tNuvcWl40: {
            objectId: 'j2gx87tw',
            name: 'tim',
            rank: 1,
            score: 0,
            connected: true,
          },
          v1S3ZSH9I: {
            objectId: 'nrpd8cuu',
            name: 'tim3',
            rank: 1,
            score: 0,
            connected: true,
          },
          x7dges268: {
            objectId: '2mzlnkdj',
            name: 'Bot 0',
            rank: 1,
            score: 0,
            connected: true,
          },
          mf8puo4zli: {
            objectId: 'jb7uz57t',
            name: 'Bot 1',
            rank: 1,
            score: 0,
            connected: true,
          },
        },
        objects: {
          vjviuu0j: {
            id: 'vjviuu0j',
            type: 'Cards',
            ownerId: 'eyuuz61j',
            items: [],
            cardsSide: 'back',
          },
          dpkkznzk: {
            id: 'dpkkznzk',
            type: 'BelkaTeam',
            ownerId: 'eyuuz61j',
            index: 0,
            gameScore: 0,
            roundScore: 0,
            color: 'black',
          },
          n95uto39: {
            id: 'n95uto39',
            type: 'BelkaTeam',
            ownerId: 'eyuuz61j',
            index: 0,
            gameScore: 0,
            roundScore: 0,
            color: 'red',
          },
          j11wmo40: {
            id: 'j11wmo40',
            type: 'BelkaEggs',
            ownerId: 'eyuuz61j',
            active: false,
          },
          m27e6npe: {
            id: 'm27e6npe',
            type: 'Timer',
            ownerId: 'eyuuz61j',
            value: -1,
          },
          sqzfxns4: {
            id: 'sqzfxns4',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          h5qrte5e: {
            id: 'h5qrte5e',
            type: 'Card',
            ownerId: '2pkegt32',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          mhreowf3: {
            id: 'mhreowf3',
            type: 'Card',
            ownerId: 'xzkhax5l',
            side: 'face',
            data: {
              value: '7',
              suit: 2,
            },
          },
          '5f098n8v': {
            id: '5f098n8v',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          '100gsr1u': {
            id: '100gsr1u',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          '6hqqxl2b': {
            id: '6hqqxl2b',
            type: 'Card',
            ownerId: '2pkegt32',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          i17tkvec: {
            id: 'i17tkvec',
            type: 'Card',
            ownerId: 'knuzidc0',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          bzs1fft9: {
            id: 'bzs1fft9',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          rr3cayrg: {
            id: 'rr3cayrg',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          qd7vzrah: {
            id: 'qd7vzrah',
            type: 'Card',
            ownerId: '2pkegt32',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          e5yfcc3r: {
            id: 'e5yfcc3r',
            type: 'Card',
            ownerId: 'knuzidc0',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          '4jkso3i4': {
            id: '4jkso3i4',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          ysvxh1gs: {
            id: 'ysvxh1gs',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          slsml765: {
            id: 'slsml765',
            type: 'Card',
            ownerId: '2pkegt32',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          mxebh4oc: {
            id: 'mxebh4oc',
            type: 'Card',
            ownerId: 'knuzidc0',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          '11u3i5h6': {
            id: '11u3i5h6',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          ph3ns1re: {
            id: 'ph3ns1re',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          '50jiyxba': {
            id: '50jiyxba',
            type: 'Card',
            ownerId: 'auldvbzh',
            side: 'face',
            data: {
              value: '10',
              suit: 2,
            },
          },
          p3717orr: {
            id: 'p3717orr',
            type: 'Card',
            ownerId: 'knuzidc0',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          wykc85oe: {
            id: 'wykc85oe',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          l0p6d69e: {
            id: 'l0p6d69e',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          saie1xy4: {
            id: 'saie1xy4',
            type: 'Card',
            ownerId: '2pkegt32',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          w4fsmein: {
            id: 'w4fsmein',
            type: 'Card',
            ownerId: 'knuzidc0',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          '5759i721': {
            id: '5759i721',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          adagc3mq: {
            id: 'adagc3mq',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          q9qjaqqn: {
            id: 'q9qjaqqn',
            type: 'Card',
            ownerId: '2pkegt32',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          x4aqz3cg: {
            id: 'x4aqz3cg',
            type: 'Card',
            ownerId: 'knuzidc0',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          fyu85cpl: {
            id: 'fyu85cpl',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          y33st9qb: {
            id: 'y33st9qb',
            type: 'Card',
            ownerId: '1yhf19c9',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          w2uo3eqi: {
            id: 'w2uo3eqi',
            type: 'Card',
            ownerId: '2pkegt32',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          popaworc: {
            id: 'popaworc',
            type: 'Card',
            ownerId: 'knuzidc0',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          '70qurbif': {
            id: '70qurbif',
            type: 'Card',
            ownerId: '8gzor99s',
            side: 'back',
            data: {
              value: '',
              suit: 0,
            },
          },
          eyuuz61j: {
            id: 'eyuuz61j',
            type: 'BelkaBoard',
            ownerId: '',
            deckId: 'vjviuu0j',
            team1Id: 'dpkkznzk',
            team2Id: 'n95uto39',
            eggsId: 'j11wmo40',
            scene: 'gameRounds',
            timerId: 'm27e6npe',
          },
          pbe3rupk: {
            id: 'pbe3rupk',
            type: 'Timer',
            ownerId: 'j2gx87tw',
            value: 23,
          },
          f678cebv: {
            id: 'f678cebv',
            type: 'Cards',
            ownerId: 'j2gx87tw',
            items: [],
            cardsSide: 'face',
          },
          '1yhf19c9': {
            id: '1yhf19c9',
            type: 'Cards',
            ownerId: 'j2gx87tw',
            items: [
              'y33st9qb',
              'adagc3mq',
              'l0p6d69e',
              'ph3ns1re',
              'ysvxh1gs',
              'rr3cayrg',
              '100gsr1u',
              'sqzfxns4',
            ],
            cardsSide: 'back',
          },
          fqrlayly: {
            id: 'fqrlayly',
            type: 'Cards',
            ownerId: 'j2gx87tw',
            items: [],
            cardsSide: 'back',
          },
          j2gx87tw: {
            id: 'j2gx87tw',
            type: 'BelkaPlayer',
            ownerId: '',
            timerId: 'pbe3rupk',
            cardSlotId: 'f678cebv',
            handId: '1yhf19c9',
            suit: 1,
            score: 0,
            teamId: 'dpkkznzk',
            trashId: 'fqrlayly',
          },
          aqc2jf5o: {
            id: 'aqc2jf5o',
            type: 'Timer',
            ownerId: 'nrpd8cuu',
          },
          jrb0tkqj: {
            id: 'jrb0tkqj',
            type: 'Cards',
            ownerId: 'nrpd8cuu',
            items: [],
            cardsSide: 'face',
          },
          '8gzor99s': {
            id: '8gzor99s',
            type: 'Cards',
            ownerId: 'nrpd8cuu',
            items: [
              '70qurbif',
              'fyu85cpl',
              '5759i721',
              'wykc85oe',
              '11u3i5h6',
              '4jkso3i4',
              'bzs1fft9',
              '5f098n8v',
            ],
            cardsSide: 'back',
          },
          dbwkdsmb: {
            id: 'dbwkdsmb',
            type: 'Cards',
            ownerId: 'nrpd8cuu',
            items: [],
            cardsSide: 'back',
          },
          nrpd8cuu: {
            id: 'nrpd8cuu',
            type: 'BelkaPlayer',
            ownerId: '',
            timerId: 'aqc2jf5o',
            cardSlotId: 'jrb0tkqj',
            handId: '8gzor99s',
            suit: -1,
            score: 0,
            teamId: 'n95uto39',
            trashId: 'dbwkdsmb',
          },
          nxd9fbtu: {
            id: 'nxd9fbtu',
            type: 'Timer',
            ownerId: '2mzlnkdj',
            value: -1,
          },
          xzkhax5l: {
            id: 'xzkhax5l',
            type: 'Cards',
            ownerId: '2mzlnkdj',
            items: ['mhreowf3'],
            cardsSide: 'face',
          },
          knuzidc0: {
            id: 'knuzidc0',
            type: 'Cards',
            ownerId: '2mzlnkdj',
            items: [
              'popaworc',
              'x4aqz3cg',
              'w4fsmein',
              'p3717orr',
              'mxebh4oc',
              'e5yfcc3r',
              'i17tkvec',
            ],
            cardsSide: 'back',
          },
          '2f45yb42': {
            id: '2f45yb42',
            type: 'Cards',
            ownerId: '2mzlnkdj',
            items: [],
            cardsSide: 'back',
          },
          '2mzlnkdj': {
            id: '2mzlnkdj',
            type: 'BelkaPlayer',
            ownerId: '',
            timerId: 'nxd9fbtu',
            cardSlotId: 'xzkhax5l',
            handId: 'knuzidc0',
            suit: -1,
            score: 0,
            teamId: 'dpkkznzk',
            trashId: '2f45yb42',
          },
          '4vpznqej': {
            id: '4vpznqej',
            type: 'Timer',
            ownerId: 'jb7uz57t',
            value: -1,
          },
          auldvbzh: {
            id: 'auldvbzh',
            type: 'Cards',
            ownerId: 'jb7uz57t',
            items: ['50jiyxba'],
            cardsSide: 'face',
          },
          '2pkegt32': {
            id: '2pkegt32',
            type: 'Cards',
            ownerId: 'jb7uz57t',
            items: [
              'w2uo3eqi',
              'q9qjaqqn',
              'saie1xy4',
              'slsml765',
              'qd7vzrah',
              '6hqqxl2b',
              'h5qrte5e',
            ],
            cardsSide: 'back',
          },
          '09xrblip': {
            id: '09xrblip',
            type: 'Cards',
            ownerId: 'jb7uz57t',
            items: [],
            cardsSide: 'back',
          },
          jb7uz57t: {
            id: 'jb7uz57t',
            type: 'BelkaPlayer',
            ownerId: '',
            timerId: '4vpznqej',
            cardSlotId: 'auldvbzh',
            handId: '2pkegt32',
            suit: -1,
            score: 0,
            teamId: 'n95uto39',
            trashId: '09xrblip',
          },
        },
        players: ['j2gx87tw', 'nrpd8cuu', '2mzlnkdj', 'jb7uz57t'],
        boardId: 'eyuuz61j',
      },
    },
    sessionId: 'v1S3ZSH9I',
    serializerId: 'schema',
  },
  common: {
    error: null,
    bet: 0,
  },
  auth: {
    email: 'tim3@mail.com',
    name: 'tim3',
    id: '',
    created: '',
    _persist: {
      version: -1,
      rehydrated: true,
    },
  },
}
