export const MOCKS_GAME_IN_PROCESS = {
  clients: {
    hCRlapK8I: 't4medrns',
    y4l0e0c79l: '58p7qzr0',
    '3rko0i9p5f': 'f0wfj24i',
    xqg2qd9m4h: 'lc6ls6j1',
  },
  objects: {
    wr14i8nz: {
      id: 'wr14i8nz',
      type: 'Cards',
      ownerId: 'ukrur3e2',
      items: ['tsfm3ho2', '00hq0bm6', '6pfiokbd', 'pk8lswua'],
      cardsSide: 'back',
    },
    '8jhv8odu': {
      id: '8jhv8odu',
      type: 'BelkaTeam',
      ownerId: 'ukrur3e2',
      index: 0,
      gameScore: 0,
      roundScore: 14,
    },
    ri4uk7zs: {
      id: 'ri4uk7zs',
      type: 'BelkaTeam',
      ownerId: 'ukrur3e2',
      index: 0,
      gameScore: 0,
      roundScore: 0,
    },
    '78w4rm4y': {
      id: '78w4rm4y',
      type: 'BelkaEggs',
      ownerId: 'ukrur3e2',
      active: false,
    },
    fpjeicez: {
      id: 'fpjeicez',
      type: 'Timer',
      ownerId: 'ukrur3e2',
      value: -1,
    },
    '6lvxeskr': {
      id: '6lvxeskr',
      type: 'Card',
      ownerId: '8gh59flt',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '7dkgjjpy': {
      id: '7dkgjjpy',
      type: 'Card',
      ownerId: 'sbv9v0tc',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    h9seczew: {
      id: 'h9seczew',
      type: 'Card',
      ownerId: 'o7a70c6o',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    gmwg8q43: {
      id: 'gmwg8q43',
      type: 'Card',
      ownerId: 'hpu5as94',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    al2nh6ls: {
      id: 'al2nh6ls',
      type: 'Card',
      ownerId: '8gh59flt',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '9mvcjuac': {
      id: '9mvcjuac',
      type: 'Card',
      ownerId: 'sbv9v0tc',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tsfm3ho2: {
      id: 'tsfm3ho2',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    pk8lswua: {
      id: 'pk8lswua',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    skogog3m: {
      id: 'skogog3m',
      type: 'Card',
      ownerId: '8gh59flt',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    rakfvvpl: {
      id: 'rakfvvpl',
      type: 'Card',
      ownerId: 'sbv9v0tc',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    labf2ypw: {
      id: 'labf2ypw',
      type: 'Card',
      ownerId: 'o7a70c6o',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    yvfprtdd: {
      id: 'yvfprtdd',
      type: 'Card',
      ownerId: 'hpu5as94',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    eyi23gpw: {
      id: 'eyi23gpw',
      type: 'Card',
      ownerId: '8gh59flt',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '7jxzhrdy': {
      id: '7jxzhrdy',
      type: 'Card',
      ownerId: 'sbv9v0tc',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '88ty0c7n': {
      id: '88ty0c7n',
      type: 'Card',
      ownerId: 'o7a70c6o',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    h15pr35v: {
      id: 'h15pr35v',
      type: 'Card',
      ownerId: 'hpu5as94',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '67mgrc0y': {
      id: '67mgrc0y',
      type: 'Card',
      ownerId: '8gh59flt',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tb1vpfcu: {
      id: 'tb1vpfcu',
      type: 'Card',
      ownerId: 'sbv9v0tc',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tk6pz8jf: {
      id: 'tk6pz8jf',
      type: 'Card',
      ownerId: 'o7a70c6o',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    t31o52og: {
      id: 't31o52og',
      type: 'Card',
      ownerId: 'hpu5as94',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '6pfiokbd': {
      id: '6pfiokbd',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    zy4czusp: {
      id: 'zy4czusp',
      type: 'Card',
      ownerId: 'sbv9v0tc',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '6u703nio': {
      id: '6u703nio',
      type: 'Card',
      ownerId: 'o7a70c6o',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ib4s7a4j: {
      id: 'ib4s7a4j',
      type: 'Card',
      ownerId: 'hpu5as94',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '05lcjaw1': {
      id: '05lcjaw1',
      type: 'Card',
      ownerId: '8gh59flt',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    lqerq3u9: {
      id: 'lqerq3u9',
      type: 'Card',
      ownerId: 'sbv9v0tc',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '8waqp8hq': {
      id: '8waqp8hq',
      type: 'Card',
      ownerId: 'o7a70c6o',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    e3g15ynb: {
      id: 'e3g15ynb',
      type: 'Card',
      ownerId: 'hpu5as94',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ggmmss5z: {
      id: 'ggmmss5z',
      type: 'Card',
      ownerId: '8gh59flt',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '00hq0bm6': {
      id: '00hq0bm6',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    nkeu7w5g: {
      id: 'nkeu7w5g',
      type: 'Card',
      ownerId: 'o7a70c6o',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '5t3jgejp': {
      id: '5t3jgejp',
      type: 'Card',
      ownerId: 'hpu5as94',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ukrur3e2: {
      id: 'ukrur3e2',
      type: 'BelkaBoard',
      ownerId: '',
      deckId: 'wr14i8nz',
      team1Id: '8jhv8odu',
      team2Id: 'ri4uk7zs',
      eggsId: '78w4rm4y',
      scene: 'gameRounds',
      timerId: 'fpjeicez',
    },
    e4czkb01: {
      id: 'e4czkb01',
      type: 'Timer',
      ownerId: 't4medrns',
      value: 27,
    },
    '1kyr4u7g': {
      id: '1kyr4u7g',
      type: 'Cards',
      ownerId: 't4medrns',
      items: [],
      cardsSide: 'face',
    },
    '8gh59flt': {
      id: '8gh59flt',
      type: 'Cards',
      ownerId: 't4medrns',
      items: ['ggmmss5z', '05lcjaw1', '67mgrc0y', 'eyi23gpw', 'skogog3m', 'al2nh6ls', '6lvxeskr'],
      cardsSide: 'back',
    },
    t4medrns: {
      id: 't4medrns',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'e4czkb01',
      name: 'tim2',
      cardSlotId: '1kyr4u7g',
      handId: '8gh59flt',
      suit: -1,
      score: 14,
      teamId: '8jhv8odu',
    },
    in1rumw8: {
      id: 'in1rumw8',
      type: 'Timer',
      ownerId: '58p7qzr0',
      value: -1,
    },
    '3zemy9ss': {
      id: '3zemy9ss',
      type: 'Cards',
      ownerId: '58p7qzr0',
      items: [],
      cardsSide: 'face',
    },
    hpu5as94: {
      id: 'hpu5as94',
      type: 'Cards',
      ownerId: '58p7qzr0',
      items: ['5t3jgejp', 'e3g15ynb', 'ib4s7a4j', 't31o52og', 'h15pr35v', 'yvfprtdd', 'gmwg8q43'],
      cardsSide: 'back',
    },
    '58p7qzr0': {
      id: '58p7qzr0',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'in1rumw8',
      name: 'Bot0',
      cardSlotId: '3zemy9ss',
      handId: 'hpu5as94',
      suit: -1,
      score: 0,
      teamId: 'ri4uk7zs',
    },
    hb9dk279: {
      id: 'hb9dk279',
      type: 'Timer',
      ownerId: 'f0wfj24i',
      value: -1,
    },
    q4xfk5tg: {
      id: 'q4xfk5tg',
      type: 'Cards',
      ownerId: 'f0wfj24i',
      items: [],
      cardsSide: 'face',
    },
    o7a70c6o: {
      id: 'o7a70c6o',
      type: 'Cards',
      ownerId: 'f0wfj24i',
      items: ['nkeu7w5g', '8waqp8hq', '6u703nio', 'tk6pz8jf', '88ty0c7n', 'labf2ypw', 'h9seczew'],
      cardsSide: 'back',
    },
    f0wfj24i: {
      id: 'f0wfj24i',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'hb9dk279',
      name: 'Bot1',
      cardSlotId: 'q4xfk5tg',
      handId: 'o7a70c6o',
      suit: 1,
      score: 0,
      teamId: '8jhv8odu',
    },
    in2g3eoa: {
      id: 'in2g3eoa',
      type: 'Timer',
      ownerId: 'lc6ls6j1',
      value: -1,
    },
    wl3z6rqh: {
      id: 'wl3z6rqh',
      type: 'Cards',
      ownerId: 'lc6ls6j1',
      items: [],
      cardsSide: 'face',
    },
    sbv9v0tc: {
      id: 'sbv9v0tc',
      type: 'Cards',
      ownerId: 'lc6ls6j1',
      items: ['lqerq3u9', 'zy4czusp', 'tb1vpfcu', '7jxzhrdy', 'rakfvvpl', '9mvcjuac', '7dkgjjpy'],
      cardsSide: 'back',
    },
    lc6ls6j1: {
      id: 'lc6ls6j1',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'in2g3eoa',
      name: 'Bot2',
      cardSlotId: 'wl3z6rqh',
      handId: 'sbv9v0tc',
      suit: -1,
      score: 0,
      teamId: 'ri4uk7zs',
    },
  },
  players: ['t4medrns', '58p7qzr0', 'f0wfj24i', 'lc6ls6j1'],
}

export const GAME_PREPARATION = {
  clients: {
    hCRlapK8I: 't4medrns',
    y4l0e0c79l: '58p7qzr0',
    '3rko0i9p5f': 'f0wfj24i',
    xqg2qd9m4h: 'lc6ls6j1',
  },
  objects: {
    wr14i8nz: {
      id: 'wr14i8nz',
      type: 'Cards',
      ownerId: 'ukrur3e2',
      items: [
        '6lvxeskr',
        '7dkgjjpy',
        'h9seczew',
        'gmwg8q43',
        'al2nh6ls',
        '9mvcjuac',
        'tsfm3ho2',
        'pk8lswua',
        'skogog3m',
        'rakfvvpl',
        'labf2ypw',
        'yvfprtdd',
        'eyi23gpw',
        '7jxzhrdy',
        '88ty0c7n',
        'h15pr35v',
        '67mgrc0y',
        'tb1vpfcu',
        'tk6pz8jf',
        't31o52og',
        '6pfiokbd',
        'zy4czusp',
        '6u703nio',
        'ib4s7a4j',
        '05lcjaw1',
        'lqerq3u9',
        '8waqp8hq',
        'e3g15ynb',
        'ggmmss5z',
        '00hq0bm6',
        'nkeu7w5g',
        '5t3jgejp',
      ],
      cardsSide: 'back',
    },
    '8jhv8odu': {
      id: '8jhv8odu',
      type: 'BelkaTeam',
      ownerId: 'ukrur3e2',
      index: 0,
      gameScore: 0,
      roundScore: 0,
    },
    ri4uk7zs: {
      id: 'ri4uk7zs',
      type: 'BelkaTeam',
      ownerId: 'ukrur3e2',
      index: 0,
      gameScore: 0,
      roundScore: 0,
    },
    '78w4rm4y': {
      id: '78w4rm4y',
      type: 'BelkaEggs',
      ownerId: 'ukrur3e2',
      active: false,
    },
    fpjeicez: {
      id: 'fpjeicez',
      type: 'Timer',
      ownerId: 'ukrur3e2',
      value: 10,
    },
    '6lvxeskr': {
      id: '6lvxeskr',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '7dkgjjpy': {
      id: '7dkgjjpy',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    h9seczew: {
      id: 'h9seczew',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    gmwg8q43: {
      id: 'gmwg8q43',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    al2nh6ls: {
      id: 'al2nh6ls',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '9mvcjuac': {
      id: '9mvcjuac',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tsfm3ho2: {
      id: 'tsfm3ho2',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    pk8lswua: {
      id: 'pk8lswua',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    skogog3m: {
      id: 'skogog3m',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    rakfvvpl: {
      id: 'rakfvvpl',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    labf2ypw: {
      id: 'labf2ypw',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    yvfprtdd: {
      id: 'yvfprtdd',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    eyi23gpw: {
      id: 'eyi23gpw',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '7jxzhrdy': {
      id: '7jxzhrdy',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '88ty0c7n': {
      id: '88ty0c7n',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    h15pr35v: {
      id: 'h15pr35v',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '67mgrc0y': {
      id: '67mgrc0y',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tb1vpfcu: {
      id: 'tb1vpfcu',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tk6pz8jf: {
      id: 'tk6pz8jf',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    t31o52og: {
      id: 't31o52og',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '6pfiokbd': {
      id: '6pfiokbd',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    zy4czusp: {
      id: 'zy4czusp',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '6u703nio': {
      id: '6u703nio',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ib4s7a4j: {
      id: 'ib4s7a4j',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '05lcjaw1': {
      id: '05lcjaw1',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    lqerq3u9: {
      id: 'lqerq3u9',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '8waqp8hq': {
      id: '8waqp8hq',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    e3g15ynb: {
      id: 'e3g15ynb',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ggmmss5z: {
      id: 'ggmmss5z',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '00hq0bm6': {
      id: '00hq0bm6',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    nkeu7w5g: {
      id: 'nkeu7w5g',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '5t3jgejp': {
      id: '5t3jgejp',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ukrur3e2: {
      id: 'ukrur3e2',
      type: 'BelkaBoard',
      ownerId: '',
      deckId: 'wr14i8nz',
      team1Id: '8jhv8odu',
      team2Id: 'ri4uk7zs',
      eggsId: '78w4rm4y',
      scene: 'initGame',
      timerId: 'fpjeicez',
    },
    e4czkb01: {
      id: 'e4czkb01',
      type: 'Timer',
      ownerId: 't4medrns',
    },
    '1kyr4u7g': {
      id: '1kyr4u7g',
      type: 'Cards',
      ownerId: 't4medrns',
      items: [],
      cardsSide: 'face',
    },
    '8gh59flt': {
      id: '8gh59flt',
      type: 'Cards',
      ownerId: 't4medrns',
      items: [],
      cardsSide: 'back',
    },
    t4medrns: {
      id: 't4medrns',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'e4czkb01',
      name: 'tim2',
      cardSlotId: '1kyr4u7g',
      handId: '8gh59flt',
      suit: -1,
      score: 0,
    },
    in1rumw8: {
      id: 'in1rumw8',
      type: 'Timer',
      ownerId: '58p7qzr0',
    },
    '3zemy9ss': {
      id: '3zemy9ss',
      type: 'Cards',
      ownerId: '58p7qzr0',
      items: [],
      cardsSide: 'face',
    },
    hpu5as94: {
      id: 'hpu5as94',
      type: 'Cards',
      ownerId: '58p7qzr0',
      items: [],
      cardsSide: 'back',
    },
    '58p7qzr0': {
      id: '58p7qzr0',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'in1rumw8',
      name: 'Bot0',
      cardSlotId: '3zemy9ss',
      handId: 'hpu5as94',
      suit: -1,
      score: 0,
    },
    hb9dk279: {
      id: 'hb9dk279',
      type: 'Timer',
      ownerId: 'f0wfj24i',
    },
    q4xfk5tg: {
      id: 'q4xfk5tg',
      type: 'Cards',
      ownerId: 'f0wfj24i',
      items: [],
      cardsSide: 'face',
    },
    o7a70c6o: {
      id: 'o7a70c6o',
      type: 'Cards',
      ownerId: 'f0wfj24i',
      items: [],
      cardsSide: 'back',
    },
    f0wfj24i: {
      id: 'f0wfj24i',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'hb9dk279',
      name: 'Bot1',
      cardSlotId: 'q4xfk5tg',
      handId: 'o7a70c6o',
      suit: -1,
      score: 0,
    },
    in2g3eoa: {
      id: 'in2g3eoa',
      type: 'Timer',
      ownerId: 'lc6ls6j1',
    },
    wl3z6rqh: {
      id: 'wl3z6rqh',
      type: 'Cards',
      ownerId: 'lc6ls6j1',
      items: [],
      cardsSide: 'face',
    },
    sbv9v0tc: {
      id: 'sbv9v0tc',
      type: 'Cards',
      ownerId: 'lc6ls6j1',
      items: [],
      cardsSide: 'back',
    },
    lc6ls6j1: {
      id: 'lc6ls6j1',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'in2g3eoa',
      name: 'Bot2',
      cardSlotId: 'wl3z6rqh',
      handId: 'sbv9v0tc',
      suit: -1,
      score: 0,
    },
  },
  players: [],
}

export const MODAL_OPEN = {
  clients: {
    hCRlapK8I: 't4medrns',
    y4l0e0c79l: '58p7qzr0',
    '3rko0i9p5f': 'f0wfj24i',
    xqg2qd9m4h: 'lc6ls6j1',
  },
  objects: {
    wr14i8nz: {
      id: 'wr14i8nz',
      type: 'Cards',
      ownerId: 'ukrur3e2',
      items: [
        'tsfm3ho2',
        '00hq0bm6',
        '6pfiokbd',
        'pk8lswua',
        '6lvxeskr',
        '5t3jgejp',
        '6u703nio',
        'tb1vpfcu',
        '8waqp8hq',
        'rakfvvpl',
        'skogog3m',
        'h15pr35v',
        'al2nh6ls',
        'yvfprtdd',
        'nkeu7w5g',
        '9mvcjuac',
        'eyi23gpw',
        'ib4s7a4j',
        'labf2ypw',
        '7dkgjjpy',
        '88ty0c7n',
        'zy4czusp',
        'ggmmss5z',
        't31o52og',
        '67mgrc0y',
        'gmwg8q43',
        'tk6pz8jf',
        'lqerq3u9',
      ],
      cardsSide: 'back',
    },
    '8jhv8odu': {
      id: '8jhv8odu',
      type: 'BelkaTeam',
      ownerId: 'ukrur3e2',
      index: 0,
      gameScore: 0,
      roundScore: 105,
    },
    ri4uk7zs: {
      id: 'ri4uk7zs',
      type: 'BelkaTeam',
      ownerId: 'ukrur3e2',
      index: 0,
      gameScore: 0,
      roundScore: 0,
    },
    '78w4rm4y': {
      id: '78w4rm4y',
      type: 'BelkaEggs',
      ownerId: 'ukrur3e2',
      active: false,
    },
    fpjeicez: {
      id: 'fpjeicez',
      type: 'Timer',
      ownerId: 'ukrur3e2',
      value: -1,
    },
    '6lvxeskr': {
      id: '6lvxeskr',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '7dkgjjpy': {
      id: '7dkgjjpy',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    h9seczew: {
      id: 'h9seczew',
      type: 'Card',
      ownerId: 'q4xfk5tg',
      side: 'face',
      data: {
        value: '9',
        suit: 2,
      },
    },
    gmwg8q43: {
      id: 'gmwg8q43',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    al2nh6ls: {
      id: 'al2nh6ls',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '9mvcjuac': {
      id: '9mvcjuac',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tsfm3ho2: {
      id: 'tsfm3ho2',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    pk8lswua: {
      id: 'pk8lswua',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    skogog3m: {
      id: 'skogog3m',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    rakfvvpl: {
      id: 'rakfvvpl',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    labf2ypw: {
      id: 'labf2ypw',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    yvfprtdd: {
      id: 'yvfprtdd',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    eyi23gpw: {
      id: 'eyi23gpw',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '7jxzhrdy': {
      id: '7jxzhrdy',
      type: 'Card',
      ownerId: 'wl3z6rqh',
      side: 'face',
      data: {
        value: '10',
        suit: 3,
      },
    },
    '88ty0c7n': {
      id: '88ty0c7n',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    h15pr35v: {
      id: 'h15pr35v',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '67mgrc0y': {
      id: '67mgrc0y',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tb1vpfcu: {
      id: 'tb1vpfcu',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    tk6pz8jf: {
      id: 'tk6pz8jf',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    t31o52og: {
      id: 't31o52og',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '6pfiokbd': {
      id: '6pfiokbd',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    zy4czusp: {
      id: 'zy4czusp',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '6u703nio': {
      id: '6u703nio',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ib4s7a4j: {
      id: 'ib4s7a4j',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '05lcjaw1': {
      id: '05lcjaw1',
      type: 'Card',
      ownerId: '1kyr4u7g',
      side: 'face',
      data: {
        value: 'J',
        suit: 3,
      },
    },
    lqerq3u9: {
      id: 'lqerq3u9',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '8waqp8hq': {
      id: '8waqp8hq',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    e3g15ynb: {
      id: 'e3g15ynb',
      type: 'Card',
      ownerId: '3zemy9ss',
      side: 'face',
      data: {
        value: 'Q',
        suit: 1,
      },
    },
    ggmmss5z: {
      id: 'ggmmss5z',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '00hq0bm6': {
      id: '00hq0bm6',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    nkeu7w5g: {
      id: 'nkeu7w5g',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    '5t3jgejp': {
      id: '5t3jgejp',
      type: 'Card',
      ownerId: 'wr14i8nz',
      side: 'back',
      data: {
        value: '',
        suit: 0,
      },
    },
    ukrur3e2: {
      id: 'ukrur3e2',
      type: 'BelkaBoard',
      ownerId: '',
      deckId: 'wr14i8nz',
      team1Id: '8jhv8odu',
      team2Id: 'ri4uk7zs',
      eggsId: '78w4rm4y',
      scene: 'gameRounds',
      timerId: 'fpjeicez',
    },
    e4czkb01: {
      id: 'e4czkb01',
      type: 'Timer',
      ownerId: 't4medrns',
      value: -1,
    },
    '1kyr4u7g': {
      id: '1kyr4u7g',
      type: 'Cards',
      ownerId: 't4medrns',
      items: ['05lcjaw1'],
      cardsSide: 'face',
    },
    '8gh59flt': {
      id: '8gh59flt',
      type: 'Cards',
      ownerId: 't4medrns',
      items: [],
      cardsSide: 'back',
    },
    t4medrns: {
      id: 't4medrns',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'e4czkb01',
      name: 'tim2',
      cardSlotId: '1kyr4u7g',
      handId: '8gh59flt',
      suit: -1,
      score: 62,
      teamId: '8jhv8odu',
    },
    in1rumw8: {
      id: 'in1rumw8',
      type: 'Timer',
      ownerId: '58p7qzr0',
      value: -1,
    },
    '3zemy9ss': {
      id: '3zemy9ss',
      type: 'Cards',
      ownerId: '58p7qzr0',
      items: ['e3g15ynb'],
      cardsSide: 'face',
    },
    hpu5as94: {
      id: 'hpu5as94',
      type: 'Cards',
      ownerId: '58p7qzr0',
      items: [],
      cardsSide: 'back',
    },
    '58p7qzr0': {
      id: '58p7qzr0',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'in1rumw8',
      name: 'Bot0',
      cardSlotId: '3zemy9ss',
      handId: 'hpu5as94',
      suit: -1,
      score: 0,
      teamId: 'ri4uk7zs',
    },
    hb9dk279: {
      id: 'hb9dk279',
      type: 'Timer',
      ownerId: 'f0wfj24i',
      value: -1,
    },
    q4xfk5tg: {
      id: 'q4xfk5tg',
      type: 'Cards',
      ownerId: 'f0wfj24i',
      items: ['h9seczew'],
      cardsSide: 'face',
    },
    o7a70c6o: {
      id: 'o7a70c6o',
      type: 'Cards',
      ownerId: 'f0wfj24i',
      items: [],
      cardsSide: 'back',
    },
    f0wfj24i: {
      id: 'f0wfj24i',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'hb9dk279',
      name: 'Bot1',
      cardSlotId: 'q4xfk5tg',
      handId: 'o7a70c6o',
      suit: 1,
      score: 43,
      teamId: '8jhv8odu',
    },
    in2g3eoa: {
      id: 'in2g3eoa',
      type: 'Timer',
      ownerId: 'lc6ls6j1',
      value: -1,
    },
    wl3z6rqh: {
      id: 'wl3z6rqh',
      type: 'Cards',
      ownerId: 'lc6ls6j1',
      items: ['7jxzhrdy'],
      cardsSide: 'face',
    },
    sbv9v0tc: {
      id: 'sbv9v0tc',
      type: 'Cards',
      ownerId: 'lc6ls6j1',
      items: [],
      cardsSide: 'back',
    },
    lc6ls6j1: {
      id: 'lc6ls6j1',
      type: 'BelkaPlayer',
      ownerId: '',
      connected: true,
      timerId: 'in2g3eoa',
      name: 'Bot2',
      cardSlotId: 'wl3z6rqh',
      handId: 'sbv9v0tc',
      suit: -1,
      score: 0,
      teamId: 'ri4uk7zs',
    },
  },
  players: ['t4medrns', '58p7qzr0', 'f0wfj24i', 'lc6ls6j1'],
}
